### ISSUE TITLE
Running the Windows 2 Unix converter on cluster

### ISSUE THREAD

**Issue by Mirandeitor** [AlexEMG/DLCutils#5]
Im running the DLCUtils function on the cluster and i get the following error:

import deeplabcut
File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/deeplabcut/init.py", line 33, in 
from deeplabcut import pose_estimation_tensorflow
File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/init.py", line 17, in 
from deeplabcut.pose_estimation_tensorflow.nnet import *
File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/nnet/init.py", line 14, in 
from deeplabcut.pose_estimation_tensorflow.nnet.losses import *
File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/nnet/losses.py", line 5, in 
import tensorflow as tf
File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/init.py", line 22, in 
from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/python/init.py", line 49, in 
from tensorflow.python import pywrap_tensorflow
File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in 
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in 
from tensorflow.python.pywrap_tensorflow_internal import *
File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in 
_pywrap_tensorflow_internal = swig_import_helper()
File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/imp.py", line 242, in load_module
return load_dynamic(name, filename, file)
File "/icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/imp.py", line 342, in load_dynamic
return _load(spec)
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by /icm/hydra/home/grid/plgmirandeitor/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Any idea what to do to solve the problem?

**Comment by AlexEMG** [comment]
I'm afraid I am not sure what the problem here is (looks like a Tensorflow installation problem, does Tensorflow work?).

Please note that with the latest version, the conversion from windows annotation files to linux format happens automatically! See DLC 2.0.4 https://github.com/AlexEMG/DeepLabCut/releases/tag/v2.0.4

The intended workflow would be:
1) create a project, extract frames, label data (on your windows computer)
2) transfer the complete project to the cluster/ colab / AWS... change the project_path in the configuration file accordingly
3) run deeplabcut.create_training_set(...) during this step it should automatically detect that the paths are in windows format, but that you are running on linux and thus convert the paths. Proceed as usual for training, evaluation & analysis (on the cluster).

**Comment by Mirandeitor** [comment]
I have digging about the problem and I think it is a problem with the gcc version. If i type:

strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX

i only get that the following libraries are available

GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH

So i think it is an admin problem because i have no permission to update that in the cluster.

Thanks your your kick answer
